spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/amms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&nullNamePatternMatchesAll=true"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #Disable execution on startup
  #http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config
  batch:
    job:
      enabled: false